AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  virtual-comics-api

  Sample SAM Template for Virtual Comics API

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  VirtualComicsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          API_URL: API_URL
          API_PUBLIC_KEY: API_PUBLIC_KEY
          API_PRIVATE_KEY: API_PRIVATE_KEY
      Events:
        VirtualComicsEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: any

  VirtualComicsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: virtual-comics-dependencies
      Description: Dependencies api
      ContentUri: src/dependencies/
      CompatibleRuntimes:
        - nodejs6.10
        - nodejs8.10
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  VirtualComicsApi:
    Description: "API Gateway endpoint URL for Prod stage for Virtual Comics function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"
  VirtualComicsFunction:
    Description: "Lambda Function ARN"
    Value: !Sub ExpressBackend.Arn
  VirtualComicsFunctionIamRole:
    Description: "Implicit IAM Role created for the function"
    Value: !Sub ExpressBackendFunctionRole.Arn
